"""Generate a tiny SYNTHETIC stand-in dataset so the pipeline can be exercised
end to end when a real dataset folder is missing.

**This data is fake.** Every path it writes contains ``_synthetic`` and the
generated tree carries a ``SYNTHETIC_DATA.txt`` marker. Never report a number
computed on it as a result.

Each image is a coloured "leaf" blob on a background, with a darker "lesion"
blob inside the leaf. Matching leaf and lesion masks are written, so mask
alignment, the CAM penalty and relevance-mass code paths can all be tested
without any real download.

Usage::

    python data/make_synthetic.py --out data/raw/_synthetic --classes 3 --per-class 20
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import numpy as np

MARKER = "SYNTHETIC_DATA.txt"

MARKER_TEXT = """This directory contains SYNTHETIC placeholder images.

They were generated by data/make_synthetic.py to exercise the pipeline when a
real dataset was unavailable. They are random shapes, not plants.

Do not report any metric computed on this data.
"""


def _draw_example(
    rng: np.random.Generator, size: int, class_idx: int
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return ``(image, leaf_mask, lesion_mask)`` for one synthetic example."""
    img = np.zeros((size, size, 3), dtype=np.uint8)

    # Background: a flat-ish colour plus noise, so background pixels carry a
    # weak class signal. That is deliberate - it lets shortcut behaviour show up.
    bg_base = np.array([140 + 20 * class_idx, 120, 100], dtype=np.float32)
    img[:] = np.clip(bg_base + rng.normal(0, 8, (size, size, 3)), 0, 255).astype(np.uint8)

    # Leaf: a filled ellipse, green-ish, jittered in position and size.
    leaf = np.zeros((size, size), dtype=np.uint8)
    cx = int(rng.integers(size // 3, 2 * size // 3))
    cy = int(rng.integers(size // 3, 2 * size // 3))
    ax = int(rng.integers(size // 5, size // 3))
    ay = int(rng.integers(size // 5, size // 3))
    angle = int(rng.integers(0, 180))
    cv2.ellipse(leaf, (cx, cy), (ax, ay), angle, 0, 360, color=1, thickness=-1)

    leaf_colour = np.array([40, 130 + 15 * class_idx, 50], dtype=np.float32)
    leaf_px = np.clip(leaf_colour + rng.normal(0, 10, (size, size, 3)), 0, 255).astype(np.uint8)
    img = np.where(leaf[..., None] == 1, leaf_px, img)

    # Lesion: a smaller blob strictly inside the leaf.
    lesion = np.zeros((size, size), dtype=np.uint8)
    lx = int(np.clip(cx + rng.integers(-ax // 2, ax // 2 + 1), 0, size - 1))
    ly = int(np.clip(cy + rng.integers(-ay // 2, ay // 2 + 1), 0, size - 1))
    lr = max(3, int(min(ax, ay) // 3))
    cv2.circle(lesion, (lx, ly), lr, color=1, thickness=-1)
    lesion = (lesion & leaf).astype(np.uint8)  # never outside the leaf

    lesion_colour = np.array([90, 70, 30], dtype=np.float32)
    lesion_px = np.clip(lesion_colour + rng.normal(0, 8, (size, size, 3)), 0, 255).astype(np.uint8)
    img = np.where(lesion[..., None] == 1, lesion_px, img)

    return img, leaf, lesion


def make_synthetic(
    out_root: Path,
    n_classes: int = 3,
    per_class: int = 20,
    size: int = 256,
    seed: int = 0,
) -> dict[str, int]:
    """Write the synthetic tree and return per-class counts.

    Layout mirrors a real dataset so loaders need no special case::

        <out_root>/color/synthetic_class_0/img_000.jpg
        data/masks/leaf/_synthetic/color/synthetic_class_0/img_000.jpg.png
        data/masks/lesion_human/_synthetic/color/synthetic_class_0/img_000.jpg.png
    """
    rng = np.random.default_rng(seed)
    out_root = Path(out_root)
    dataset_name = out_root.name

    repo = Path(__file__).resolve().parents[1]
    leaf_root = repo / "data" / "masks" / "leaf" / dataset_name / "color"
    lesion_root = repo / "data" / "masks" / "lesion_human" / dataset_name / "color"

    out_root.mkdir(parents=True, exist_ok=True)
    (out_root / MARKER).write_text(MARKER_TEXT, encoding="utf-8")

    counts: dict[str, int] = {}
    for c in range(n_classes):
        cls = f"synthetic_class_{c}"
        img_dir = out_root / "color" / cls
        img_dir.mkdir(parents=True, exist_ok=True)
        (leaf_root / cls).mkdir(parents=True, exist_ok=True)
        (lesion_root / cls).mkdir(parents=True, exist_ok=True)

        for i in range(per_class):
            img, leaf, lesion = _draw_example(rng, size, c)
            name = f"img_{i:03d}.jpg"
            cv2.imwrite(str(img_dir / name), cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
            cv2.imwrite(str(leaf_root / cls / f"{name}.png"), leaf * 255)
            cv2.imwrite(str(lesion_root / cls / f"{name}.png"), lesion * 255)
        counts[cls] = per_class

    return counts


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate a synthetic stand-in dataset.")
    ap.add_argument("--out", default="data/raw/_synthetic")
    ap.add_argument("--classes", type=int, default=3)
    ap.add_argument("--per-class", type=int, default=20)
    ap.add_argument("--size", type=int, default=256)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    repo = Path(__file__).resolve().parents[1]
    out = Path(args.out)
    if not out.is_absolute():
        out = repo / out

    counts = make_synthetic(out, args.classes, args.per_class, args.size, args.seed)
    total = sum(counts.values())
    print(f"SYNTHETIC data written to {out}")
    print(f"  {len(counts)} classes, {total} images (+ leaf and lesion masks)")
    print("  THIS DATA IS FAKE - never report metrics computed on it.")


if __name__ == "__main__":
    main()
